In [4]:
import numpy as np

In [4]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [5]:
complex_array = np.array([1 + 2j, 3 + 4j], dtype=complex)
print(complex_array)

[1.+2.j 3.+4.j]


In [6]:
sub_array = array[1:4]
print(sub_array)

[2 3 4]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_array = arr1 + arr2
print(sum_array)

[5 7 9]


In [14]:
arr = np.array([10, 20, 30, 40])
filtered_array = arr[arr > 25]
print(filtered_array)

[30 40]


In [8]:
first_element = arr[0]
print(first_element)

10


In [10]:
math_scores = np.array([85, 72, 90])
science_scores = np.array([78, 88, 95])
average_scores = np.array([75, 85])

passed_in_subjects = np.vstack((math_scores > average_scores[0], science_scores > average_scores[1]))
print(passed_in_subjects)

[[ True False  True]
 [False  True  True]]


In [43]:
random_numbers = np.random.rand(2, 3)
print(random_numbers)

[[0.38277389 0.74033765 0.74405532]
 [0.00925658 0.72314896 0.29130825]]


In [45]:
normal_data = np.random.randn(2, 3)
print(normal_data)

[[-0.22277191  0.86547509 -1.44766311]
 [ 1.52860917  1.27335359  0.28155573]]
